language: c++

cache: ccache

git:
  depth: 10

env:
  global:
    - JOBS_IF_PARALLEL=2
    - PACKAGE=harftex-bin-${ARCH}-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz

matrix:
  include:
    - os: linux
      env: ARCH=x86_64
      dist: xenial
    - os: osx
      env: ARCH=x86_64
      install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - os: linux
      env: ARCH=i386
      services: docker
      script: |
        docker run \
        -e JOBS_IF_PARALLEL="${JOBS_IF_PARALLEL}" \
        -v ${TRAVIS_BUILD_DIR}:/luatex -w /luatex \
        -it i386/debian:jessie sh -c \
        "apt-get update; apt-get install -y --no-install-recommends bash gcc g++ make; ./build.sh --parallel"

addons:
  homebrew:
    packages:
      - ccache

# Avoid timestamping issues
before_script:
  - find . -name \*.info -exec touch '{}' \;
  - touch ./source/texk/web2c/web2c/web2c-lexer.c
  - touch ./source/texk/web2c/web2c/web2c-parser.c
  - touch ./source/texk/web2c/web2c/web2c-parser.h

script:
  - ./build.sh --parallel

before_deploy:
  - tar czvf ${PACKAGE} -C build/texk/web2c harftex

deploy:
  provider: releases
  api_key:
    secure: Bbr/7B8wjDyVrzFq4dBUJbfKawfctNGNkB7OZcKtCFLETnnHZi9nk8fYDlqmQQP30lZOLFWAkgnAbd8ZK81Bgr65Wq5ziHRvYG2hc4BsDk+2yArntkG+q+h2b4KiVgYeu9ThLYCVUHtT4zgD4BEEf9V0gmMK5UiWushdXPRnCkz1EgFlYD52b+u/qN5BBIWuWTTKoHdR3aJMc7H1s1lXz3UI63ZiUeH8BkxOOZI1llg0nh3o+Rnzpp7E+fO0TsdXFWKwKJLHhetShBF+V8LiA+BmR2GIfEbVg8H/471Hey4pWDosOq1+EUGmFfqewZnOoOriou7f16Rc/vRqU1TVoPbZzOgi4LWjgweCoGZqEbe3y6RxIevFSf3UcCQD6qFnvQQEicXvxlLa7zUm9SHHthbeL+4jwK4t0cDPCC4xbwYJYXbQEPtYKyUwG71jpx9YCatesOwgqqztnmpIYeUDesobC1xtwZCqbAAL8P4jC4UtM0RZ92XsRPpgBVTaHBq2aMF6R//E8pxQ9pHp+HAaFaQ2EcMLxX/hVk5eeY7IRObmJcwK+qDqTi83WyyKn6SwyPemwse89b5TG4AXIYDDHQq8L+WqA9vozW82cwpN/HO9BdERP/f2L620MiRLE4DEoKNnnVnDdUpu7P+MKxujJtG6uf0yt3WLKhlMjUomWHU=
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
    repo: khaledhosny/harftex
    branch: master
